EaseInCollege/urls.py
from django.conf.urls import url
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path,include
from django.views.static import serve

from EaseInCollege import settings
from app1 import views

urlpatterns = [
    path('', views.loginn, name="login"),
    path('app1/', include('app1.urls')),
    path('admin/', admin.site.urls),
    path('api-auth/', include('rest_framework.urls')),
    url(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
]
urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app1/urls.py
from django.conf.urls.static import static
from django.urls import path

from EaseInCollege import settings
from . import views

from .views import CadastroAlunoAPIView, CadastrosAlunosAPIView, CadastroFuncionarioAPIView, \
    CadastrosFuncionariosAPIView, EventoAPIView, EventosAPIView, EmpregoAPIView, EmpregosAPIView, \
    SugestaoAPIView, SugestoesAPIView, FuncionarioListView, FuncionarioUpdateView, \
    FuncionarioDeleteView, FuncionarioCreateView, AlunoCreateView, AlunoListView, AlunoUpdateView, \
    AlunoDeleteView, EventoCreateView, EventoListView, EventoUpdateView, EventoDeleteView, EmpregoCreateView, \
    EmpregoListView, EmpregoUpdateView, EmpregoDeleteView, SugestaoCreateView, SugestaoListView, SugestaoUpdateView, \
    SugestaoDeleteView

app_name = "app1"

urlpatterns = [
    path('', views.imagem_eventos, name="listar_eventos"),
    path('login', views.loginn, name='login'),
    path('logout', views.logoutt, name='logout'),
    path('indexx', views.indexx, name='indexx'),

######################################################################################################

    # GET /funcionario/cadastrar
    path('funcionario/cadastrar', FuncionarioCreateView.as_view(), name="cadastra_funcionario"),

    # GET /funcionarios
    path('funcionarios/', FuncionarioListView.as_view(), name="lista_funcionarios"),

    # GET/POST /funcionario/{pk}
    path('funcionario/<pk>', FuncionarioUpdateView.as_view(), name="atualiza_funcionario"),

    # GET/POST /funcionarios/excluir/{pk}
    path('funcionario/excluir/<pk>', FuncionarioDeleteView.as_view(), name="deleta_funcionario"),

######################################################################################################

    # GET /aluno/cadastrar
    path('aluno/cadastrar', AlunoCreateView.as_view(), name="cadastra_aluno"),

    # GET /alunos
    path('alunos/', AlunoListView.as_view(), name="lista_alunos"),

    # GET/POST /aluno/{pk}
    path('aluno/<pk>', AlunoUpdateView.as_view(), name="atualiza_aluno"),

    # GET/POST /alunos/excluir/{pk}
    path('aluno/excluir/<pk>', AlunoDeleteView.as_view(), name="deleta_aluno"),

######################################################################################################

    # GET /evento/cadastrar
    path('evento/cadastrar', EventoCreateView.as_view(), name="cadastra_evento"),

    # GET /eventos
    path('eventos/', EventoListView.as_view(), name="lista_eventos"),

    # GET/POST /evento/{pk}
    path('evento/<pk>', EventoUpdateView.as_view(), name="atualiza_evento"),

    # GET/POST /eventos/excluir/{pk}
    path('evento/excluir/<pk>', EventoDeleteView.as_view(), name="deleta_evento"),

######################################################################################################

    # GET /emprego/cadastrar
    path('emprego/cadastrar', EmpregoCreateView.as_view(), name="cadastra_emprego"),

    # GET /empregos
    path('empregos/', EmpregoListView.as_view(), name="lista_empregos"),

    # GET/POST /emprego/{pk}
    path('emprego/<pk>', EmpregoUpdateView.as_view(), name="atualiza_emprego"),

    # GET/POST /emprego/excluir/{pk}
    path('emprego/excluir/<pk>', EmpregoDeleteView.as_view(), name="deleta_emprego"),

######################################################################################################

    # GET /sugestao/cadastrar
    path('sugestao/cadastrar', SugestaoCreateView.as_view(), name="cadastra_sugestao"),

    # GET /sugestoes
    path('sugestoes/', SugestaoListView.as_view(), name="lista_sugestoes"),

    # GET/POST /sugestao/{pk}
    path('sugestao/<pk>', SugestaoUpdateView.as_view(), name="atualiza_sugestao"),

    # GET/POST /sugestao/excluir/{pk}
    path('sugestao/excluir/<pk>', SugestaoDeleteView.as_view(), name="deleta_sugestao"),

    # API ---------------------- ###################################################################

    path('APIcadastro_aluno/', CadastrosAlunosAPIView.as_view(), name='cadastros_alunos'),
    path('APIcadastro_aluno/<int:pk>/', CadastroAlunoAPIView.as_view(), name='cadastro_aluno'),

    path('APIcadastro_funcionario/', CadastrosFuncionariosAPIView.as_view(), name='cadastros_funcionarios'),
    path('APIcadastro_funcionario/<int:pk>/', CadastroFuncionarioAPIView.as_view(), name='cadastro_funcionario'),

    path('APIevento/', EventosAPIView.as_view(), name='eventos'),
    path('APIevento/<int:pk>/', EventoAPIView.as_view(), name='evento'),

    path('APIemprego/', EmpregosAPIView.as_view(), name='empregos'),
    path('APIemprego/<int:pk>/', EmpregoAPIView.as_view(), name='emprego'),

    path('APIsugestao/', SugestoesAPIView.as_view(), name='sugestoes'),
    path('APIsugestao/<int:pk>/', SugestaoAPIView.as_view(), name='sugestao'),
]

templates/app3/layouts/base.html
<!DOCTYPE html>
 <html lang="pt-br">
   {% load static %}

     <head>
           <meta charset="UTF-8">
           <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
           <meta http-equiv="X-UA-Compatible" content="ie=edge">

           <!-- Title -->
           <title>{% block title %}Foxcon Sistemas{% endblock %}</title>

           <!-- Favicon -->
           <link rel="shortcut icon"  href="{% static 'app2/imgs/easelogo.png' %}" type="image/png">

           <!-- Arquivos CSS -->
           <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
           <link rel="stylesheet" type="text/css" href="{% static "app2/css/master.css" %}">
           <link rel="stylesheet" type="text/css" href="{% static 'app2/css/font-awesome.min.css' %}">
	       <link rel="stylesheet"  href="{% static 'app2/css/style_default.css' %}">


           <!-- Boxicons CDN Link -->
           <link href='https://unpkg.com/boxicons@2.0.7/css/boxicons.min.css' rel='stylesheet'>


		<!-- Global site tag (gtag.js) - Google Analytics -->
		<script async src="https://www.googletagmanager.com/gtag/js?id=UA-147102043-1"></script>
		<script>
			window.dataLayer = window.dataLayer || [];
			function gtag(){dataLayer.push(arguments);}
			gtag('js', new Date());
			gtag('config', 'UA-147102043-1');
		</script>

     </head>

<body>

   <div id="fb-root"></div>
         <script async defer crossorigin="anonymous"
             src="https://connect.facebook.net/pt_BR/sdk.js#xfbml=1&version=v3.2&appId=3056845927722925&autoLogAppEvents=1"></script>

 <div class="sidebar">
    <div class="logo-details" style="padding-top: 10px">
      <img class="icon" alt="Base Security" src="{% static "app2/imgs/easelogo.png" %}" data-aos-easing="ease-out" data-aos="fade-in" data-aos-duration="550" height="180px" >
        <i class='bx bx-menu' id="btn"  style="font-size: 30px"></i>
    </div>
    <ul class="nav-list" style="padding-left: 0px; font-size: 30px">

        <!-- Somente Usúario Cadastrado -->

            {% if user.is_authenticated %}

      <li>
        <a href="{% url 'app1:indexx' %}" style="font-size: 20px; color: #141764">
          <i class='bx bx-home' style="font-size: 30px"></i>
          <span class="links_name" style="font-size: 19px">Início</span>
        </a>
         <span class="tooltip" style="font-size: 19px">Início</span>
      </li>


        <!-- Somente Administrador -->
              {% if user.is_staff %}
     <li>
       <a href="{% url 'app1:lista_alunos' %}" style="font-size: 20px; color: #141764">
         <i class='bx bx-id-card'  style="font-size: 30px"></i>
         <span class="links_name" style="font-size: 19px">Aluno</span>
       </a>
       <span class="tooltip">Aluno</span>
     </li>

     <li>
       <a href="{% url 'app1:lista_funcionarios' %}" style="font-size: 20px; color: #141764">
         <i class='bx bx-id-card'  style="font-size: 30px"></i>
         <span class="links_name" style="font-size: 19px">Funcionário</span>
       </a>
       <span class="tooltip">Funcionário</span>
     </li>

     <li>
       <a href="{% url 'app1:lista_eventos' %}" style="font-size: 20px; color: #141764">
         <i class='bx bx-id-card'  style="font-size: 30px"></i>
         <span class="links_name" style="font-size: 19px">Evento</span>
       </a>
       <span class="tooltip">Evento</span>
     </li>

     <li>
       <a href="{% url 'app1:lista_empregos' %}" style="font-size: 20px; color: #141764">
         <i class='bx bx-id-card'  style="font-size: 30px"></i>
         <span class="links_name" style="font-size: 19px">Emprego</span>
       </a>
       <span class="tooltip">Emprego</span>
     </li>

     <li>
       <a href="{% url 'app1:lista_sugestoes' %}" style="font-size: 20px; color: #141764">
         <i class='bx bx-id-card'  style="font-size: 30px"></i>
         <span class="links_name" style="font-size: 19px">Sugestão</span>
       </a>
       <span class="tooltip">Sugestão</span>
     </li>

     <li>

       <a href="{% url 'admin:index' %}"  style="font-size: 20px; color: #141764">
         <i class='bx bx-cog'  style="font-size: 30px"></i>
         <span class="links_name" style="font-size: 19px">Admin</span>
       </a>
       <span class="tooltip">Admin</span>
     </li>
              {% endif %}
        {% endif %}
     <li class="profile">
         <div class="profile-details">
           <div class="name_job" >
             <div class="name" style="font-size: 13px">Usuário</div>
             <div class="job" style="font-size: 17px">{{ user.first_name }}</div>
           </div>
              <!-- Logout do Sistema -->
        <a href="{% url 'app1:logout' %}">
         <i class='bx bx-log-out' id="log_out"  style="font-size: 30px"></i>
        </a>
         </div>
     </li>
    </ul>
  </div>

  <section class="home-section">
                        <!-- Conteúdo do site -->
                     {% block conteudo %}{% endblock %}
  </section>

     <div id="fundo" style="background-color: #bdc4e0;"></div>
               <style>
	                 .page_content img { max-width: 100% !important; height: auto !important; }
               </style>

		<!-- <script src="{static 'app2/js/jquery-scrolltofixed.js' %}"></script> -->

		<div vw class="enabled" style="padding-top: 40px">
			<div vw-access-button class="active"></div>
				<div vw-plugin-wrapper>
				<div class="vw-plugin-top-wrapper"></div>
			</div>
		</div>

		<script src="https://vlibras.gov.br/app/vlibras-plugin.js"></script>
		<script>
			new window.VLibras.Widget('https://vlibras.gov.br/app');
		</script>

<script>
    $(function () {
  $('[data-toggle="tooltip"]').tooltip()
})
</script>

    <style>
	    div[vw] { top: 50% !important; }
    </style>

                         <!-- Scripts .js -->
        <script src="{% static 'app2/js/jquery.min.js'%}"></script>
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
		<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
        <script src="{% static 'app2/js/events.js' %}"></script>
        <script src="{% static 'app2/js/ScriptBase.js' %}"></script>
        <script src="{% static 'app2/js/scripts.js' %}"></script>
        <script src="{% static 'app2/js/bootstrap.min.js'%}"></script>
</body>
 </html>