EaseInCollege/urls.py
from django.conf.urls import url
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path,include
from django.views.static import serve

from EaseInCollege import settings
from app1 import views

urlpatterns = [
    path('', views.loginn, name="login"),
    path('app1/', include('app1.urls')),
    path('admin/', admin.site.urls),
    path('api-auth/', include('rest_framework.urls')),
    url(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
]
urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app1/urls.py
from django.conf.urls.static import static
from django.urls import path

from EaseInCollege import settings
from . import views

from .views import CadastroAlunoAPIView, CadastrosAlunosAPIView, CadastroFuncionarioAPIView, \
    CadastrosFuncionariosAPIView, EventoAPIView, EventosAPIView, EmpregoAPIView, EmpregosAPIView, \
    SugestaoAPIView, SugestoesAPIView, FuncionarioListView, FuncionarioUpdateView, \
    FuncionarioDeleteView, FuncionarioCreateView, AlunoCreateView, AlunoListView, AlunoUpdateView, \
    AlunoDeleteView, EventoCreateView, EventoListView, EventoUpdateView, EventoDeleteView, EmpregoCreateView, \
    EmpregoListView, EmpregoUpdateView, EmpregoDeleteView, SugestaoCreateView, SugestaoListView, SugestaoUpdateView, \
    SugestaoDeleteView

app_name = "app1"

urlpatterns = [
    path('', views.imagem_eventos, name="listar_eventos"),
    path('login', views.loginn, name='login'),
    path('logout', views.logoutt, name='logout'),
    path('indexx', views.indexx, name='indexx'),

######################################################################################################

    # GET /funcionario/cadastrar
    path('funcionario/cadastrar', FuncionarioCreateView.as_view(), name="cadastra_funcionario"),

    # GET /funcionarios
    path('funcionarios/', FuncionarioListView.as_view(), name="lista_funcionarios"),

    # GET/POST /funcionario/{pk}
    path('funcionario/<pk>', FuncionarioUpdateView.as_view(), name="atualiza_funcionario"),

    # GET/POST /funcionarios/excluir/{pk}
    path('funcionario/excluir/<pk>', FuncionarioDeleteView.as_view(), name="deleta_funcionario"),

######################################################################################################

    # GET /aluno/cadastrar
    path('aluno/cadastrar', AlunoCreateView.as_view(), name="cadastra_aluno"),

    # GET /alunos
    path('alunos/', AlunoListView.as_view(), name="lista_alunos"),

    # GET/POST /aluno/{pk}
    path('aluno/<pk>', AlunoUpdateView.as_view(), name="atualiza_aluno"),

    # GET/POST /alunos/excluir/{pk}
    path('aluno/excluir/<pk>', AlunoDeleteView.as_view(), name="deleta_aluno"),

######################################################################################################

    # GET /evento/cadastrar
    path('evento/cadastrar', EventoCreateView.as_view(), name="cadastra_evento"),

    # GET /eventos
    path('eventos/', EventoListView.as_view(), name="lista_eventos"),

    # GET/POST /evento/{pk}
    path('evento/<pk>', EventoUpdateView.as_view(), name="atualiza_evento"),

    # GET/POST /eventos/excluir/{pk}
    path('evento/excluir/<pk>', EventoDeleteView.as_view(), name="deleta_evento"),

######################################################################################################

    # GET /emprego/cadastrar
    path('emprego/cadastrar', EmpregoCreateView.as_view(), name="cadastra_emprego"),

    # GET /empregos
    path('empregos/', EmpregoListView.as_view(), name="lista_empregos"),

    # GET/POST /emprego/{pk}
    path('emprego/<pk>', EmpregoUpdateView.as_view(), name="atualiza_emprego"),

    # GET/POST /emprego/excluir/{pk}
    path('emprego/excluir/<pk>', EmpregoDeleteView.as_view(), name="deleta_emprego"),

######################################################################################################

    # GET /sugestao/cadastrar
    path('sugestao/cadastrar', SugestaoCreateView.as_view(), name="cadastra_sugestao"),

    # GET /sugestoes
    path('sugestoes/', SugestaoListView.as_view(), name="lista_sugestoes"),

    # GET/POST /sugestao/{pk}
    path('sugestao/<pk>', SugestaoUpdateView.as_view(), name="atualiza_sugestao"),

    # GET/POST /sugestao/excluir/{pk}
    path('sugestao/excluir/<pk>', SugestaoDeleteView.as_view(), name="deleta_sugestao"),

    # API ---------------------- ###################################################################

    path('APIcadastro_aluno/', CadastrosAlunosAPIView.as_view(), name='cadastros_alunos'),
    path('APIcadastro_aluno/<int:pk>/', CadastroAlunoAPIView.as_view(), name='cadastro_aluno'),

    path('APIcadastro_funcionario/', CadastrosFuncionariosAPIView.as_view(), name='cadastros_funcionarios'),
    path('APIcadastro_funcionario/<int:pk>/', CadastroFuncionarioAPIView.as_view(), name='cadastro_funcionario'),

    path('APIevento/', EventosAPIView.as_view(), name='eventos'),
    path('APIevento/<int:pk>/', EventoAPIView.as_view(), name='evento'),

    path('APIemprego/', EmpregosAPIView.as_view(), name='empregos'),
    path('APIemprego/<int:pk>/', EmpregoAPIView.as_view(), name='emprego'),

    path('APIsugestao/', SugestoesAPIView.as_view(), name='sugestoes'),
    path('APIsugestao/<int:pk>/', SugestaoAPIView.as_view(), name='sugestao'),
]

templates/app3/evento/atualiza.html
{% extends "app3/layouts/base.html" %}

{% load widget_tweaks %}

{% block title %}Atualização de Evento{% endblock %}

{% block conteudo %}

<style>
.testbutton {
  font-family: "Poppins" , sans-serif;
  font-weight: bold;
  font-size: 14px;
  padding: 10px 20px;
  border-radius: 45px;
  border: none;
  box-shadow: 1px 1px 1px #00F929;
  background: #FFFFFF;
  transition: 0.3s;
}
.testbutton:hover {
  color: #FFFFFF !important;
  background: #33CF1B;
  background: linear-gradient(to top, #33CF1B, #0C81E8);
  text-decoration: none;
  border: 2px groove #FFFFFF;
}
.testbutton:active {
  transform: translatey(8px);
}
.testbuttonv {
  font-family: "Poppins" , sans-serif;
  font-weight: bold;
  font-size: 14px;
  padding: 10px 20px;
  border-radius: 45px;
  border: none;
  box-shadow: 1px 1px 1px #BF0000;
  background: #FFFFFF;
  transition: 0.3s;
}
.testbuttonv:hover {
  color: #FFFFFF !important;
  background: #800000;
  background: linear-gradient(to top, #FF0000, #E87715);
  text-decoration: none;
  border: 2px groove #FFFFFF;
}
.testbuttonv:active {
  transform: translatey(8px);
}
.container a .tool{
  position: fixed;
  z-index: 3;
  color: white;
  background:#4e555b;
  box-shadow: 0 5px 10px rgba(0, 0, 0, 0.3);
  padding: 6px 12px;
  border-radius: 4px;
  font-size: 15px;
  opacity: 0;
  transition: 0s;
  pointer-events: none;
  white-space: nowrap;
  font-weight: 400;
  margin-left: 10px;
}
.container a:hover .tool{
  opacity: 1;
  pointer-events: auto;
  transition: all 0.4s ease;
  transform: translateY(-50%);
  top: 76%;
}
</style>


<div class="container" style="padding-top: 50px; margin-left: 90px; width: 900px; display: flex">
  <div class="row">
    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
      <div class="card">
        <div class="card-body">
          <h5 class="card-title">Atualizar Dados Cadastrais de Evento</h5>
          <form enctype="multipart/form-data" method="post">
            <!-- Não se esqueça dessa tag -->
            {% csrf_token %}

                                        <!-- Nome -->
                    <div class="input-group mb-3">
                         <div class="input-group-prepend">
                               <span class="input-group-text">Título</span>
                         </div>
                            {% render_field form.titulo class+="form-control" %}
                    </div>

                                         <!-- Curso -->
                    <div class="input-group mb-3">
                         <div class="input-group-prepend">
                               <span class="input-group-text">Categoria</span>
                         </div>
                            {% render_field form.categoria class+="form-control" %}
                         <div id="imendaHTMLcategoria"></div>
                         <a href="#" id="btnAdicionaCategoria" ></a>
                    </div>
                                        <!-- Período -->
                    <div class="input-group mb-3">
                         <div class="input-group-prepend">
                               <span class="input-group-text">Data</span>
                         </div>
                            {% render_field form.data class+="form-control" %}
                    </div>
                                             <!-- Turma-->
                    <div class="input-group mb-3">
                         <div class="input-group-prepend">
                               <span class="input-group-text">Hora</span>
                         </div>
                            {% render_field form.hora class+="form-control" %}
                    </div>
                                        <!-- Email -->
                    <div class="input-group mb-3">
                         <div class="input-group-prepend">
                               <span class="input-group-text">Local</span>
                         </div>
                            {% render_field form.local class+="form-control" placeholder="nome@exemplo.com" %}
                    </div>
                                        <!-- Senha -->
                    <div class="input-group mb-3">
                         <div class="input-group-prepend">
                               <span class="input-group-text">Rua</span>
                         </div>
                            {% render_field form.rua class+="form-control" %}
                    </div>
                                           <!-- Telefone -->
                    <div class="input-group mb-3">
                         <div class="input-group-prepend">
                               <span class="input-group-text">Número</span>
                         </div>
                            {% render_field form.numero class+="form-control" placeholder="(43)00000-0000" %}
                    </div>
                                        <!-- CPF -->
                    <div class="input-group mb-3">
                         <div class="input-group-prepend">
                               <span class="input-group-text">Imagem</span>
                         </div>
                            {% render_field form.imagem class+="form-control" %}
                    </div>
                                                            <!-- CPF -->
                    <div class="input-group mb-3">
                         <div class="input-group-prepend">
                               <span class="input-group-text">Carga</span>
                         </div>
                            {% render_field form.carga class+="form-control" %}
                    </div>
                                                            <!-- CPF -->
                    <div class="input-group mb-3">
                         <div class="input-group-prepend">
                               <span class="input-group-text">Descrição</span>
                         </div>
                            {% render_field form.descricao class+="form-control" %}
                    </div>
                                                            <!-- CPF -->
                    <div class="input-group mb-3">
                         <div class="input-group-prepend">
                               <span class="input-group-text">Link</span>
                         </div>
                            {% render_field form.link class+="form-control" %}
                    </div>

            <hr/>
            <div class="text-center">
                    <a href="{% url 'app1:lista_eventos' %}">
                        <i class='bx bx-x testbuttonv'
                           style="border: none; font-size: 45px; padding-right: 20px; color: #BF0000">
                        </i>
                        <span class="tool">Cancelar</span>
                    </a>
                    <a>
                       <button class='bx bx-check testbutton'
                            style="border: none; font-size: 45px; padding-right: 20px; color: #2AAB16">
                       </button>
                        <span class="tool">Atualizar</span>
                    </a>
            </div>
              <hr>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

templates/app3/evento/cadastra.html
<!DOCTYPE html>
{% extends "app3/layouts/base.html" %}

{% load widget_tweaks %}
{% load static %}
<html lang="pt-br">
{% block title %}Cadastro de Alunos{% endblock %}

<body>
{% block conteudo %}

<style>
.testbutton {
  font-family: "Poppins" , sans-serif;
  font-weight: bold;
  font-size: 14px;
  padding: 10px 20px;
  border-radius: 45px;
  border: none;
  box-shadow: 1px 1px 1px #00F929;
  background: #FFFFFF;
  transition: 0.3s;
}
.testbutton:hover {
  color: #FFFFFF !important;
  background: #33CF1B;
  background: linear-gradient(to top, #33CF1B, #0C81E8);
  text-decoration: none;
  border: 2px groove #FFFFFF;
}
.testbutton:active {
  transform: translatey(8px);
}
.testbuttonv {
  font-family: "Poppins" , sans-serif;
  font-weight: bold;
  font-size: 14px;
  padding: 10px 20px;
  border-radius: 45px;
  border: none;
  box-shadow: 1px 1px 1px #BF0000;
  background: #FFFFFF;
  transition: 0.3s;
}
.testbuttonv:hover {
  color: #FFFFFF !important;
  background: #800000;
  background: linear-gradient(to top, #FF0000, #E87715);
  text-decoration: none;
  border: 2px groove #FFFFFF;
}
.testbuttonv:active {
  transform: translatey(8px);
}
.container a .tool{
  position: fixed;
  z-index: 3;
  color: white;
  background:#4e555b;
  box-shadow: 0 5px 10px rgba(0, 0, 0, 0.3);
  padding: 6px 12px;
  border-radius: 4px;
  font-size: 15px;
  opacity: 0;
  transition: 0s;
  pointer-events: none;
  white-space: nowrap;
  font-weight: 400;
  margin-left: 10px;
}
.container a:hover .tool{
  opacity: 1;
  pointer-events: auto;
  transition: all 0.4s ease;
  transform: translateY(-50%);
  top: 78%;
}
</style>

     <div class="container" style="padding-top: 25px; padding-bottom: 25px; width: 500px; display: flex">
       <div class="row">
         <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
           <div class="card">
             <div class="card-body">
                <h5 class="card-title">Cadastro de Evento</h5>
                <p class="card-text">Complete o formulário abaixo para cadastrar um novo <code>Evento.</code></p>

                <form enctype="multipart/form-data" method="POST">
                    {% csrf_token %}
                                        <!-- Nome -->
                    <div class="input-group mb-3">
                         <div class="input-group-prepend">
                               <span class="input-group-text">Título</span>
                         </div>
                            {% render_field form.titulo class+="form-control" %}
                    </div>

                                         <!-- Curso -->
                    <div class="input-group mb-3">
                         <div class="input-group-prepend">
                               <span class="input-group-text">Categoria</span>
                         </div>
                            {% render_field form.categoria class+="form-control" %}
                         <div id="imendaHTMLcategoria"></div>
                         <a href="#" id="btnAdicionaCategoria" ></a>
                    </div>
                                        <!-- Período -->
                    <div class="input-group mb-3">
                         <div class="input-group-prepend">
                               <span class="input-group-text">Data</span>
                         </div>
                            {% render_field form.data class+="form-control" %}
                    </div>
                                             <!-- Turma-->
                    <div class="input-group mb-3">
                         <div class="input-group-prepend">
                               <span class="input-group-text">Hora</span>
                         </div>
                            {% render_field form.hora class+="form-control" %}
                    </div>
                                        <!-- Email -->
                    <div class="input-group mb-3">
                         <div class="input-group-prepend">
                               <span class="input-group-text">Local</span>
                         </div>
                            {% render_field form.local class+="form-control" %}
                    </div>
                                        <!-- Senha -->
                    <div class="input-group mb-3">
                         <div class="input-group-prepend">
                               <span class="input-group-text">Rua</span>
                         </div>
                            {% render_field form.rua class+="form-control" %}
                    </div>
                                           <!-- Telefone -->
                    <div class="input-group mb-3">
                         <div class="input-group-prepend">
                               <span class="input-group-text">Número</span>
                         </div>
                            {% render_field form.numero class+="form-control" %}
                    </div>
                                        <!-- CPF -->
                    <div class="input-group mb-3">
                         <div class="input-group-prepend">
                               <span class="input-group-text">Imagem</span>
                         </div>
                            {% render_field form.imagem class+="form-control" %}
                    </div>
                                                            <!-- CPF -->
                    <div class="input-group mb-3">
                         <div class="input-group-prepend">
                               <span class="input-group-text">Carga</span>
                         </div>
                            {% render_field form.carga class+="form-control" %}
                    </div>
                                                            <!-- CPF -->
                    <div class="input-group mb-3">
                         <div class="input-group-prepend">
                               <span class="input-group-text">Descrição</span>
                         </div>
                            {% render_field form.descricao class+="form-control" %}
                    </div>
                                                            <!-- CPF -->
                    <div class="input-group mb-3">
                         <div class="input-group-prepend">
                               <span class="input-group-text">Link</span>
                         </div>
                            {% render_field form.link class+="form-control" %}
                    </div>

                       <hr>
                            <div class="text-center">
                                <a href="{% url 'app1:lista_eventos' %}">
                                    <i class='bx bx-x testbuttonv'
                                      style="border: none; font-size: 45px; padding-right: 20px; color: #BF0000">
                                    </i>
                                    <span class="tool">Cancelar</span>
                                </a>
                                <a>
                                   <button type="submit" class='bx bx-check testbutton'
                                       style="border: none; font-size: 45px; padding-right: 20px; color: #2AAB16">
                                   </button>
                                    <span class="tool">Cadastrar</span>
                                </a>
                            </div>
                    <hr>
                </form>
             </div>
           </div>
         </div>
       </div>
     </div>
{% endblock %}
</body>
</html>

templates/app3/evento/exclui.html
<!-- Estendemos do template base -->
{% extends "app3/layouts/base.html" %}

<!-- Bloco que define o <title></title> da nossa página -->
{% block title %}Exlusão de Evento{% endblock %}

<!-- Bloco de conteúdo da nossa página -->
{% block conteudo %}

<style>
.testbuttonc {
  font-family: "Poppins" , sans-serif;
  font-weight: bold;
  font-size: 14px;
  padding: 10px 20px;
  border-radius: 45px;
  border: none;
  box-shadow: 1px 1px 1px #BF0000;
  background: #FFFFFF;
  transition: 0.3s;
}
.testbuttonc:hover {
  color: #FFFFFF !important;
  background: #800000;
  background: linear-gradient(to top, #FF0000, #E87715);
  text-decoration: none;
  border: 2px groove #FFFFFF;
}
.testbuttonc:active {
  transform: translatey(8px);
}
.testbutton {
  font-family: "Poppins" , sans-serif;
  font-weight: bold;
  font-size: 14px;
  padding: 10px 20px;
  border-radius: 45px;
  border: none;
  box-shadow: 1px 1px 1px #0C81E8 ;
  background: #FFFFFF;
  transition: 0.3s;
}
.testbutton:hover {
  color: #FFFFFF !important;
  background: #0C81E8 ;
  background: linear-gradient(to top, #0C81E8, #66EE74);
  text-decoration: none;
  border: 2px groove #FFFFFF;
}
.testbutton:active {
  transform: translatey(8px);
}
.container a .tool{
  position: fixed;
  z-index: 3;
  color: white;
  background:#4e555b;
  box-shadow: 0 5px 10px rgba(0, 0, 0, 0.3);
  padding: 6px 12px;
  border-radius: 4px;
  font-size: 15px;
  opacity: 0;
  transition: 0s;
  pointer-events: none;
  white-space: nowrap;
  font-weight: 400;
  margin-left: 10px;
}
.container a:hover .tool{
  opacity: 1;
  pointer-events: auto;
  transition: all 0.4s ease;
  transform: translateY(-50%);
  top: auto;
}
</style>

  <div class="container" style="padding-top: 50px; margin-left: 90px; width: 700px; display: flex">
    <div class="card">
      <div class="card-body">
        <h5 class="card-title">Exclusão de Evento</h5>

        <p class="card-text">
          Você tem certeza que quer excluir o evento <b>{{ evento.titulo }}</b>?
        </p>

        <form method="post">
          {% csrf_token %}

          <hr />
          <div class="text-right">
            <a href="{% url 'app1:lista_eventos' %}" class="">
                <i class='bx bx-share testbutton' style="font-size: 35px; padding-right: 20px; border: none"></i>
                <span class="tool">Voltar</span>
            </a>
            <a>
                <button class='bx bx-user-x testbuttonc' style="font-size: 40px;color: #BF0000; padding-right: 20px; border: none"></button>
                <span class="tool">Excluir</span>
            </a>
          </div>
        </form>
      </div>
    </div>
  </div>
{% endblock %}

templates/app3/evento/lista.html
{% extends "app3/layouts/base.html" %}

{% block title %}Lista de Eventos{% endblock %}
  {% load static %}
{% block conteudo %}

 <style>
.testbutton {
  font-family: "Poppins" , sans-serif;
  font-weight: bold;
  font-size: 14px;
  padding: 10px 20px;
  border-radius: 45px;
  border: none;
  box-shadow: 1px 1px 1px #2AAB16;
  background: #FFFFFF;
  transition: 0.3s;
}
.testbutton:hover {
  color: #FFFFFF !important;
  background: #33CF1B;
  background: linear-gradient(to top, #2AAB16, #0C81E8);
  text-decoration: none;
  border: 2px groove #FFFFFF;
}
.testbutton:active {
  transform: translatey(8px);
}
.effectEx {
  color: red;
  font-size: 30px;
}
.effectEx:hover {
  color: #B10B11;
}
.effectEx:active {
    transform: translateY(4px);
}
.effectEd {
  font-size: 30px;
}
.effectEd:active {
    transform: translateY(4px);
}
.container a .tool{
  position: fixed;
  z-index: 3;
  color: white;
  background:#4e555b;
  box-shadow: 0 5px 10px rgba(0, 0, 0, 0.3);
  padding: 6px 12px;
  border-radius: 4px;
  font-size: 15px;
  opacity: 0;
  transition: 0s;
  pointer-events: none;
  white-space: nowrap;
  font-weight: 400;
  margin-left: 10px;
}
.container a:hover .tool{
  opacity: 1;
  pointer-events: auto;
  transition: all 0.4s ease;
  transform: translateY(-50%);
  top: auto;
}
 </style>

<div class="container" style="padding: 60px 0px; margin-left: 120px; width: 1380px; display: flex">
  <div class="row">
    <div class="col-lg-15 col-md-12 col-sm-12 col-xs-12" style="padding: 0px">
      <div class="card">
        <div class="card-body" style="padding-bottom: 10px">
          <h5 class="card-title">Lista de Eventos</h5>

          {% if eventos|length > 0 %}
            <p class="card-text">
              Aqui está a lista de <code>Eventos</code> cadastrados.
            </p>

            <div class="search-list">
            <table class="table" id="myTable">
              <thead class="thead-dark">
              <tr>
                <th scope="col">Título</th>
                <th scope="col">Categoria</th>
                <th scope="col">Data</th>
                <th scope="col">Hora</th>
                <th scope="col">Local</th>
                <th scope="col">Rua</th>
                <th scope="col">Número</th>
                <th scope="col">Carga Horária</th>
                <th scope="col">Link</th>
                  <th scope="col">Banner</th>
                <th scope="col" class="text-center">Ações</th>
              </tr>
              </thead>
              <tbody>
              {% for evento in eventos %}
                <tr>
                  <th scope="row">{{ evento.titulo }}</th>
                  <td>{{ evento.categoria }}</td>
                  <td>{{ evento.data }}</td>
                  <td>{{ evento.hora }}</td>
                  <td>{{ evento.local }}</td>
                  <td>{{ evento.rua }}</td>
                  <td>{{ evento.numero }}</td>
                  <td>{{ evento.carga }}</td>
                  <td>{{ evento.link }}</td>
                  <td><img src="{{ evento.imagem.url }}" style="width: 124px;"></td>
                  <td class="text-center">
                    <a href="{% url 'app1:atualiza_evento' pk=evento.id %}">
                      <i class='bx bx-edit effectEd'></i>
                        <span class="tool">Atualizar</span>
                    </a>
                    <a href="{% url 'app1:deleta_evento' pk=evento.id %}">
                      <i class='bx bx-trash effectEx'></i>
                        <span class="tool">Excluir</span>
                    </a>
                  </td>
                </tr>
              {% endfor %}
              </tbody>
            </table>
            </div>
        {% else %}
          <div class="text-center mt-5 mb-5 jumbotron">
            <h5>Nenhum <code>Evento</code> cadastrado ainda.</h5>
          </div>
        {% endif %}
          <hr />
          <div class="text-center" style="padding-top: 5px; padding-bottom: 5px">
            <a href="{% url 'app1:cadastra_evento' %}">
                <i class='bx bx-user-plus testbutton' style="border: none; padding-right: 20px;
                  color: #2AAB16; font-size: 40px"></i>
                <span class="tool">Cadastrar Evento</span>
            </a>
          </div>
        <hr>
        </div>
      </div>
    </div>
  </div>
</div>

<script>

$(document).ready(function() {
    var baseUrl  = 'http://127.0.0.1:8000/';
    var filter   = $('#filter');

    $(filter).change(function() {
        var filter = $(this).val();
        window.location.href = baseUrl + '?filter=' + filter;
    });
});

</script>
{% endblock %}